# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit_login_user = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_login_user.setGeometry(QtCore.QRect(100, 90, 201, 31))
        self.lineEdit_login_user.setObjectName("lineEdit_login_user")
        self.lineEdit_login_passwd = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_login_passwd.setGeometry(QtCore.QRect(100, 140, 201, 31))
        self.lineEdit_login_passwd.setText("")
        self.lineEdit_login_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_login_passwd.setObjectName("lineEdit_login_passwd")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 51, 16))
        self.label_2.setObjectName("label_2")
        self.ptn_login = QtWidgets.QPushButton(Dialog)
        self.ptn_login.setGeometry(QtCore.QRect(80, 220, 93, 28))
        self.ptn_login.setObjectName("ptn_login")
        self.ptn_exit = QtWidgets.QPushButton(Dialog)
        self.ptn_exit.setGeometry(QtCore.QRect(220, 220, 93, 28))
        self.ptn_exit.setObjectName("ptn_exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_login_user.setText(_translate("Dialog", "wuyubo"))
        self.label.setText(_translate("Dialog", "帐号"))
        self.label_2.setText(_translate("Dialog", "密码"))
        self.ptn_login.setText(_translate("Dialog", "登录"))
        self.ptn_exit.setText(_translate("Dialog", "退出"))
